global.paymentterms={data:[
    { _id:'0',	name :	'None' },
    { _id:'7',	name :	'7 Days' },
    { _id:'30',	name :	'30 Days' },
    { _id:'45',	name :	'45 Days' },
    { _id:'60',	name :	'60 Days' },
]}
global.customertype={data:[
    { _id:'Customer',	name :	'Customer' },
    { _id:'Retailer',	name :	'Retailer' },
    { _id:'Wholesaler',	name :	'Wholesaler' },
]}
global.gsttype={data:[
    { _id:'Consumer',	name :	'Consumer' },
    { _id:'UnregisteresBusiness',	name :	'UnregisteresBusiness' },
    { _id:'Regular',	name :	'Regular' },
    { _id:'Composition',	name :	'Composition' },    
    { _id:'Overseas',	name :	'Overseas' },
    { _id:'SpecialEconomicZone',	name :	'SpecialEconomicZone' },
]}
global.state ={ data : [
    { _id:'AN',	name :	'Andaman and Nicobar Islands' },
    { _id:'AP',	name :	'Andhra Pradesh' },
    { _id:'AR',	name :	'Arunachal Pradesh' },
    { _id:'AS',	name :	'Assam' },
    { _id:'BR',	name :	'Bihar' },
    { _id:'CG',	name :	'Chandigarh' },
    { _id:'CH',	name :	'Chhattisgarh' },
    { _id:'DH',	name :	'Dadra and Nagar Haveli' },
    { _id:'DD',	name :	'Daman and Diu' },
    { _id:'DL',	name :	'Delhi' },
    { _id:'GA',	name :	'Goa' },
    { _id:'GJ',	name :	'Gujarat' },
    { _id:'HR',	name :	'Haryana' },
    { _id:'HP',	name :	'Himachal Pradesh' },
    { _id:'JK',	name :	'Jammu and Kashmir' },
    { _id:'JH',	name :	'Jharkhand' },
    { _id:'KA',	name :	'Karnataka' },
    { _id:'KL',	name :	'Kerala' },
    { _id:'LD',	name :	'Lakshadweep' },
    { _id:'MP',	name :	'Madhya Pradesh '},
    { _id:'MH',	name :	'Maharashtra' },
    { _id:'MN',	name :	'Manipur' },
    { _id:'ML',	name :	'Meghalaya' },
    { _id:'MZ',	name :	'Mizoram' },
    { _id:'NL',	name :	'Nagaland' },
    { _id:'OR',	name :	'Odisha' },
    { _id:'PY',	name :	'Puducherry' },
    { _id:'PB',	name :	'Punjab' },
    { _id:'RJ',	name :	'Rajasthan' },
    { _id:'SK',	name :	'Sikkim '},
    { _id:'TN',	name :	'Tamil Nadu' },
    { _id:'TS',	name :	'Telangana' },
    { _id:'TR',	name :	'Tripura '},
    { _id:'UK',	name :	'Uttar Pradesh' },
    { _id:'UP',	name :	'Uttarakhand' },
    { _id:'WB',	name :	'West Bengal' },
]
}